name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  binaries:
    name: Build release binaries
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: ttyper-x86_64-unknown-linux-gnu.tar.gz
            cross: true

          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            name: ttyper-x86_64-unknown-linux-musl.tar.gz
            cross: true

          - target: i686-unknown-linux-musl
            os: ubuntu-latest
            name: ttyper-i686-unknown-linux-musl.tar.gz
            cross: true

          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            name: ttyper-aarch64-unknown-linux-musl.tar.gz
            cross: true

          - target: arm-unknown-linux-musleabihf
            os: ubuntu-latest
            name: ttyper-arm-unknown-linux-musleabihf.tar.gz
            cross: true

          - target: x86_64-apple-darwin
            os: macos-latest
            name: ttyper-x86_64-apple-darwin.tar.gz
            cross: false

          - target: aarch64-apple-darwin
            os: macos-latest
            name: ttyper-aarch64-apple-darwin.tar.gz
            cross: false

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: ttyper-x86_64-pc-windows-msvc.zip
            cross: false

          - target: i686-pc-windows-msvc
            os: windows-latest
            name: ttyper-i686-pc-windows-msvc.zip
            cross: false

          - target: aarch64-pc-windows-msvc
            os: windows-latest
            name: ttyper-aarch64-pc-windows-msvc.zip
            cross: false

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        if: matrix.cross
        run: cargo install cross --locked

      - name: Build (cross)
        if: matrix.cross
        run: cross build --release --locked --target ${{ matrix.target }}
        env:
          NO_RESOURCES: true

      - name: Build (native)
        if: "!matrix.cross"
        run: cargo build --release --locked --target ${{ matrix.target }}
        env:
          NO_RESOURCES: true

      - name: Prepare artifacts [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          strip ttyper.exe
          7z a ../../../${{ matrix.name }} ttyper.exe
          cd -

      - name: Prepare artifacts [Unix]
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          strip ttyper || true
          tar czvf ../../../${{ matrix.name }} ttyper
          cd -

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

  github-release:
    name: GitHub Release
    needs: binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Generate checksums
        run: for file in ttyper-*/ttyper-*; do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ttyper-*/ttyper-*
